// export const STORE_CREATE_SUCCESS = 'STORE_CREATE_SUCCESS';

export const STORE_DATA_REQUEST = 'STORE_DATA_REQUEST';
export const STORE_DATA_SUCCESS = 'STORE_DATA_SUCCESS';
export const STORE_DATA_FAIL = 'STORE_DATA_FAIL';

export const STORE_UPDATE_REQUEST = 'STORE_UPDATE_REQUEST';
export const STORE_UPDATE_SUCCESS = 'STORE_UPDATE_SUCCESS';
export const STORE_UPDATE_FAIL = 'STORE_UPDATE_FAIL';
